package rust

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
)

const wireModuleTemplate = `// This file is auto-generated by VIIPER codegen. DO NOT EDIT.

/// Trait for device input types that can be serialized to wire protocol bytes.
///
/// Input types represent data sent from the client to the device (client-to-server).
pub trait DeviceInput {
    /// Serialize this input to wire protocol bytes (little-endian).
    fn to_bytes(&self) -> Vec<u8>;
}

/// Trait for device output types that can be deserialized from wire protocol bytes.
///
/// Output types represent data received from the device (server-to-client).
pub trait DeviceOutput: Sized {
    /// Deserialize this output from wire protocol bytes (little-endian).
    fn from_bytes(buf: &[u8]) -> Result<Self, crate::error::ViiperError>;
}
`

func generateWireModule(logger *slog.Logger, srcDir string) error {
	logger.Debug("Generating wire.rs module")
	outputFile := filepath.Join(srcDir, "wire.rs")

	f, err := os.Create(outputFile)
	if err != nil {
		return fmt.Errorf("create file: %w", err)
	}
	defer f.Close()

	if _, err := f.WriteString(wireModuleTemplate); err != nil {
		return fmt.Errorf("write template: %w", err)
	}

	logger.Info("Generated wire.rs", "file", outputFile)
	return nil
}
