package udecx

import (
	"regexp"
	"strings"
	"testing"
)

func TestNativeControllerNamesDeviceBeforeAssigningSecurity(t *testing.T) {
	controller := normalizedContract(nativeContractSource(t,
		"native", "udecx", "driver", "Controller.c"))
	requireContractOrder(t, controller,
		"WdfDeviceInitSetCharacteristics( DeviceInit, FILE_DEVICE_SECURE_OPEN | FILE_AUTOGENERATED_DEVICE_NAME, FALSE);",
		"status = WdfDeviceInitAssignSDDLString(DeviceInit, &sddl);")
}

func TestNativeConfigurationSelectionDoesNotEnterResetProtocol(t *testing.T) {
	device := normalizedContract(nativeCFunction(t,
		nativeContractSource(t, "native", "udecx", "driver", "Device.c"),
		"ViiperEvtEndpointsConfigure"))
	requireContractOrder(t, device,
		"case UdecxEndpointsConfigureTypeDeviceInitialize:",
		"ConfigureParams->EndpointsToConfigureCount",
		"ViiperActivateEndpoint( ConfigureParams->EndpointsToConfigure[endpointIndex], FALSE);",
		"WdfRequestComplete(Request, STATUS_SUCCESS);",
		"return;",
		"case UdecxEndpointsConfigureTypeDeviceConfigurationChange:",
		"ConfigureParams->EndpointsToConfigureCount",
		"ViiperActivateEndpoint( ConfigureParams->EndpointsToConfigure[endpointIndex], FALSE);",
		"WdfRequestComplete(Request, STATUS_SUCCESS);",
		"return;",
		"case UdecxEndpointsConfigureTypeInterfaceSettingChange:")
	if strings.Contains(device, "ViiperUdeOperationDeviceReset") ||
		strings.Contains(device, "ViiperBeginAcknowledgedDeviceReset") {
		t.Fatal("dynamic endpoint configuration can enter the device-reset protocol")
	}
}

func TestNativePostEnumerationResetDoesNotBlockEnumerationOnUserMode(t *testing.T) {
	device := nativeContractSource(t, "native", "udecx", "driver", "Device.c")
	header := nativeContractSource(t, "native", "udecx", "driver", "ViiperUde.h")
	create := normalizedContract(nativeCFunction(t, device, "ViiperCreateVirtualDevice"))

	if strings.Contains(create, "callbacks.EvtUsbDeviceReset") ||
		strings.Contains(device, "ViiperEvtUsbDeviceReset") ||
		strings.Contains(header, "EVT_UDECX_USB_DEVICE_POST_ENUMERATION_RESET") {
		t.Fatal("post-enumeration reset can block child enumeration on a user-mode acknowledgement")
	}
	configure := normalizedContract(nativeCFunction(t, device, "ViiperEvtEndpointsConfigure"))
	requireContractOrder(t, configure,
		"case UdecxEndpointsConfigureTypeDeviceConfigurationChange:",
		"WdfRequestComplete(Request, STATUS_SUCCESS);",
		"return;")
}

func TestNativeInitialAttachOpensWorkingStateBeforePlugIn(t *testing.T) {
	device := normalizedContract(nativeCFunction(t,
		nativeContractSource(t, "native", "udecx", "driver", "Device.c"),
		"ViiperCreateVirtualDevice"))
	requireContractOrder(t, device,
		"InterlockedExchange(&deviceContext->InD0, TRUE);",
		"ViiperClaimDeviceSlot(",
		"UdecxUsbDevicePlugIn(device, &plugOptions);")
}

func TestNativeSuperSpeedPortsUseControllerGlobalNumbering(t *testing.T) {
	header := nativeContractSource(t, "native", "udecx", "driver", "ViiperUde.h")
	controller := nativeContractSource(t, "native", "udecx", "driver", "Controller.c")
	device := normalizedContract(nativeCFunction(t,
		nativeContractSource(t, "native", "udecx", "driver", "Device.c"),
		"ViiperCreateVirtualDevice"))

	for _, required := range []string{
		"#define VIIPER_UDE_USB20_PORT_COUNT VIIPER_UDE_MAX_DEVICES",
		"#define VIIPER_UDE_USB30_PORT_COUNT VIIPER_UDE_MAX_DEVICES",
	} {
		if !strings.Contains(header, required) {
			t.Fatalf("native controller topology lost %q", required)
		}
	}
	for _, required := range []string{
		"udeConfig.NumberOfUsb20Ports = (USHORT)VIIPER_UDE_USB20_PORT_COUNT;",
		"udeConfig.NumberOfUsb30Ports = (USHORT)VIIPER_UDE_USB30_PORT_COUNT;",
	} {
		if !strings.Contains(controller, required) {
			t.Fatalf("native controller creation lost %q", required)
		}
	}
	requireContractOrder(t, device,
		"if (speed == UdecxUsbSuperSpeed)",
		"plugOptions.Usb30PortNumber = (USHORT)(VIIPER_UDE_USB20_PORT_COUNT + slot + 1);",
		"else",
		"plugOptions.Usb20PortNumber = (USHORT)(slot + 1);")

	const usb20Ports = MaxDevices
	for slot := 0; slot < MaxDevices; slot++ {
		usb20Port := slot + 1
		usb30Port := usb20Ports + slot + 1
		if usb20Port < 1 || usb20Port > MaxDevices ||
			usb30Port < MaxDevices+1 || usb30Port > 2*MaxDevices {
			t.Fatalf("slot %d maps to USB2=%d USB3=%d", slot, usb20Port, usb30Port)
		}
	}
}

func TestNativeControllerEstablishesIdlePolicyBeforeUdeCxEmulation(t *testing.T) {
	controller := normalizedContract(nativeCFunction(t,
		nativeContractSource(t, "native", "udecx", "driver", "Controller.c"),
		"ViiperEvtDeviceAdd"))
	requireContractOrder(t, controller,
		"status = WdfDeviceCreate(&DeviceInit, &attributes, &device);",
		"WDF_DEVICE_POWER_POLICY_IDLE_SETTINGS_INIT( &idleSettings, IdleCannotWakeFromS0);",
		"status = WdfDeviceAssignS0IdleSettings(device, &idleSettings);",
		"status = UdecxWdfDeviceAddUsbDeviceEmulation(device, &udeConfig);")
	if strings.Contains(controller, "Start-Sleep") || strings.Contains(controller, "WdfTimer") {
		t.Fatal("controller enumeration policy must not hide lifecycle races with timing workarounds")
	}
}

func TestNativeBrokerDispatchUsesIndependentCursorAndEndpointFIFO(t *testing.T) {
	broker := nativeContractSource(t, "native", "udecx", "driver", "Broker.c")
	device := nativeContractSource(t, "native", "udecx", "driver", "Device.c")
	header := nativeContractSource(t, "native", "udecx", "driver", "ViiperUde.h")

	for _, required := range []string{
		"LIST_ENTRY AdmissionEntry;",
		"BOOLEAN AdmissionLinked;",
		"ULONG NextDispatchSlot;",
		"LIST_ENTRY AdmissionQueue;",
	} {
		if !strings.Contains(header, required) {
			t.Fatalf("native dispatch contract lost %q", required)
		}
	}
	if !strings.Contains(device,
		"InitializeListHead(&endpointContext->AdmissionQueue);") {
		t.Fatal("endpoint admission FIFO is not initialized before broker use")
	}
	if strings.Contains(broker, "ViiperHasEarlierUnpublishedAdmissionLocked") {
		t.Fatal("native dispatch still performs the controller-wide admission-order scan")
	}

	allocate := normalizedContract(nativeCFunction(t, broker, "ViiperAllocatePendingSlot"))
	requireContractOrder(t, allocate,
		"pending->AdmissionLinked = TRUE;",
		"InsertTailList(&endpointContext->AdmissionQueue, &pending->AdmissionEntry);",
		"ControllerContext->NextPendingSlot = (index + 1) % VIIPER_UDE_MAX_PENDING_OPERATIONS;")

	head := normalizedContract(nativeCFunction(t, broker, "ViiperAdmissionCanPublishLocked"))
	requireContractOrder(t, head,
		"if (!Pending->AdmissionLinked || Pending->Endpoint == WDF_NO_HANDLE)",
		"endpointContext = ViiperGetEndpointContext(Pending->Endpoint);",
		"return endpointContext->AdmissionQueue.Flink == &Pending->AdmissionEntry;")

	dispatch := normalizedContract(nativeCFunction(t, broker, "ViiperDispatchAvailable"))
	if strings.Contains(dispatch, "NextPendingSlot") {
		t.Fatal("allocation cursor is still coupled to broker dispatch")
	}
	requireContractOrder(t, dispatch,
		"controllerContext->NextDispatchSlot + index",
		"ViiperAdmissionCanPublishLocked(pending)",
		"controllerContext->NextDispatchSlot = (candidate + 1)",
		"ViiperUnlinkAdmissionLocked(pending)")
}

func TestNativeBrokerAdmissionRetirementCannotStrandSuccessor(t *testing.T) {
	broker := nativeContractSource(t, "native", "udecx", "driver", "Broker.c")

	clear := normalizedContract(nativeCFunction(t, broker, "ViiperClearSlotLocked"))
	requireContractOrder(t, clear,
		"ViiperUnlinkAdmissionLocked(pending);",
		"pending->Request = WDF_NO_HANDLE;")

	cancel := normalizedContract(nativeCFunction(t, broker, "ViiperEvtUrbCancel"))
	requireContractOrder(t, cancel,
		"dispatchSuccessor = pending->AdmissionLinked;",
		"ViiperUnlinkAdmissionLocked(pending);",
		"WdfSpinLockRelease(controllerContext->BrokerLock);",
		"if (dispatchSuccessor)",
		"ViiperDispatchAvailable(controller);")

	queue := normalizedContract(nativeCFunction(t, broker, "ViiperQueueUrb"))
	requireContractOrder(t, queue,
		"pending->State = ViiperUdePendingDpcCompletion;",
		"ViiperUnlinkAdmissionLocked(pending);",
		"if (queueCancelledCompletion)",
		"ViiperQueueUrbCompletion(",
		"ViiperDispatchAvailable(deviceContext->Controller);")

	abort := normalizedContract(nativeCFunction(t, broker, "ViiperAbortMatchingOperations"))
	requireContractOrder(t, abort,
		"pending->AbortPending = TRUE;",
		"ViiperUnlinkAdmissionLocked(pending);")
}

func TestNativeBrokerPublishingCancelCannotMissDispatchWake(t *testing.T) {
	// WdfRequestUnmarkCancelable is allowed to return STATUS_CANCELLED before
	// EvtRequestCancel has run. Model the worst ordering: the old dispatcher
	// scans while the publishing admission is still linked, finds no eligible
	// successor, and returns. The later callback must both unlink and explicitly
	// wake a new dispatch pass.
	type admission struct {
		linked bool
		state  string
	}
	head := admission{linked: true, state: "publishing"}
	successor := admission{linked: true, state: "queued"}
	canPublishSuccessor := func() bool {
		return successor.linked && !head.linked
	}

	if canPublishSuccessor() {
		t.Fatal("successor published ahead of the same-endpoint head")
	}
	oldDispatchReturned := true // it scanned before EvtRequestCancel ran
	dispatchWake := false
	if head.linked {
		dispatchWake = true
		head.linked = false
		head.state = "dpc-completion"
	}
	if !oldDispatchReturned || !dispatchWake || !canPublishSuccessor() {
		t.Fatal("publishing-head cancellation failed to wake its queued successor")
	}
}

func TestNativeBrokerIndependentCursorEliminatesCommonFullWrap(t *testing.T) {
	const slots = 4096
	scan := func(start, target int) int {
		for offset := 0; offset < slots; offset++ {
			if (start+offset)%slots == target {
				return offset + 1
			}
		}
		return slots
	}

	// The old scheduler advanced the allocation cursor after choosing slot 0,
	// then reused it as the dispatch start.  Its only queued operation was the
	// last slot inspected after wrapping the entire table.
	if got := scan(1, 0); got != slots {
		t.Fatalf("coupled-cursor baseline inspected %d slots, want %d", got, slots)
	}
	if got := scan(0, 0); got != 1 {
		t.Fatalf("independent dispatch cursor inspected %d slots, want 1", got)
	}

	allocationCursor := 0
	dispatchCursor := 0
	for iteration := 0; iteration < slots*2; iteration++ {
		allocated := allocationCursor
		allocationCursor = (allocated + 1) % slots
		if got := scan(dispatchCursor, allocated); got != 1 {
			t.Fatalf("iteration %d inspected %d slots, want 1", iteration, got)
		}
		dispatchCursor = (allocated + 1) % slots
	}
}

func TestNativeBrokerEndpointFIFOModelsPublishAndCancelOrdering(t *testing.T) {
	type admission struct {
		id       int
		endpoint int
	}
	queues := map[int][]admission{}
	appendAdmission := func(item admission) {
		queues[item.endpoint] = append(queues[item.endpoint], item)
	}
	canPublish := func(item admission) bool {
		queue := queues[item.endpoint]
		return len(queue) != 0 && queue[0].id == item.id
	}
	retire := func(item admission) {
		queue := queues[item.endpoint]
		if len(queue) == 0 || queue[0].id != item.id {
			t.Fatalf("retired non-head admission %+v from %+v", item, queue)
		}
		queues[item.endpoint] = queue[1:]
	}

	a1 := admission{id: 1, endpoint: 0x01}
	a2 := admission{id: 2, endpoint: 0x01}
	b1 := admission{id: 3, endpoint: 0x82}
	appendAdmission(a1)
	appendAdmission(a2)
	appendAdmission(b1)
	if !canPublish(a1) || canPublish(a2) || !canPublish(b1) {
		t.Fatal("per-endpoint heads did not preserve FIFO order and cross-endpoint concurrency")
	}

	retire(a1) // publication
	if !canPublish(a2) {
		t.Fatal("publication did not expose the next same-endpoint admission")
	}

	a3 := admission{id: 4, endpoint: 0x01}
	appendAdmission(a3)
	retire(a2) // cancellation/abort uses the same unlink transition
	if !canPublish(a3) {
		t.Fatal("cancellation did not expose the next same-endpoint admission")
	}
}

func TestNativeFastInputSubmissionAvoidsSecondKMDFQueueHop(t *testing.T) {
	controller := nativeContractSource(t, "native", "udecx", "driver", "Controller.c")
	ioctl := nativeContractSource(t, "native", "udecx", "driver", "Ioctl.c")
	header := nativeContractSource(t, "native", "udecx", "driver", "ViiperUde.h")
	all := controller + ioctl + header
	if strings.Contains(all, "WDFQUEUE InputQueue;") ||
		strings.Contains(all, "context->InputQueue") ||
		strings.Contains(all, "ViiperEvtInputIoDeviceControl") {
		t.Fatal("native input still crosses the redundant parallel KMDF queue")
	}

	queues := normalizedContract(nativeCFunction(t, controller, "ViiperCreateQueues"))
	requireContractOrder(t, queues,
		"WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(&queueConfig, WdfIoQueueDispatchParallel);",
		"queueConfig.EvtIoDeviceControl = ViiperEvtIoDeviceControlRoute;",
		"WDF_IO_QUEUE_CONFIG_INIT(&queueConfig, WdfIoQueueDispatchSequential);",
		"queueConfig.EvtIoDeviceControl = ViiperEvtIoDeviceControl;")

	route := normalizedContract(nativeCFunction(t, ioctl, "ViiperEvtIoDeviceControlRoute"))
	requireContractOrder(t, route,
		"InterlockedCompareExchange(&context->ShuttingDown, 0, 0)",
		"if (IoControlCode == IOCTL_VIIPER_UDE_SUBMIT_INPUT_REPORT)",
		"status = ViiperSubmitInputReport(Queue, Request);",
		"WdfRequestComplete(Request, status);",
		"return;",
		"WdfRequestForwardToIoQueue(Request, context->ControlQueue)")
	if strings.Contains(route, "WdfRequestForwardToIoQueue(Request, context->InputQueue)") {
		t.Fatal("hot input report is still forwarded before completion")
	}
}

func TestNativeCachedInputReadyUsesCompletionDPCWithoutWorkerHop(t *testing.T) {
	device := nativeContractSource(t, "native", "udecx", "driver", "Device.c")
	header := nativeContractSource(t, "native", "udecx", "driver", "ViiperUde.h")
	if strings.Contains(device+header, "InputReadyWorkItem") ||
		strings.Contains(device+header, "ViiperEvtFastInputWorkItem") {
		t.Fatal("cached input delivery still crosses a generic system work item")
	}

	createQueue := normalizedContract(nativeCFunction(t, device, "ViiperCreateEndpointQueue"))
	if !strings.Contains(createQueue, "attributes.ExecutionLevel = WdfExecutionLevelPassive;") {
		t.Fatal("manual fast-input queue no longer pins ReadyNotify to PASSIVE_LEVEL")
	}
	ready := normalizedContract(nativeCFunction(t, device, "ViiperEvtFastInputQueueReady"))
	requireContractOrder(t, ready,
		"ViiperEndpointOperationStarted(endpoint);",
		"WdfWaitLockAcquire(endpointContext->InputLock, NULL);",
		"for (;;)",
		"WdfIoQueueRetrieveNextRequest(Queue, &request)",
		"ViiperPrepareCachedInputUrb(endpoint, request);",
		"ViiperCompleteRetrievedInputUrb(endpoint, request, completionStatus);",
		"WdfWaitLockRelease(endpointContext->InputLock);",
		"ViiperEndpointOperationCompleted(endpoint);")
	if strings.Count(ready, "ViiperEndpointOperationStarted(endpoint);") != 2 {
		t.Fatal("ReadyNotify must hold one callback rundown reference and one per queued DPC")
	}
	if strings.Contains(ready, "WdfWorkItemEnqueue") ||
		strings.Contains(ready, "UdecxUrbComplete(") {
		t.Fatal("ReadyNotify either retains a worker hop or completes a UDE URB synchronously")
	}

	complete := normalizedContract(nativeCFunction(t, device, "ViiperCompleteRetrievedInputUrb"))
	if !strings.Contains(complete, "ViiperQueueUrbCompletion(") {
		t.Fatal("cached input no longer transfers terminal completion to the shared DPC")
	}
}

func TestNativeFastInputQueuesTransitionsButCoalescesIdleCadence(t *testing.T) {
	header := nativeContractSource(t, "native", "udecx", "include", "ViiperUdeProtocol.h")
	if !strings.Contains(header, "#define VIIPER_UDE_INPUT_REPORT_TRANSITION 0x01") {
		t.Fatal("native ABI does not classify discrete input transitions")
	}
	device := nativeContractSource(t, "native", "udecx", "driver", "Device.c")
	submit := normalizedContract(nativeCFunction(t, device, "ViiperSubmitInputReport"))
	requireContractOrder(t, submit,
		"if ((input->Flags & VIIPER_UDE_INPUT_REPORT_TRANSITION) != 0 &&",
		"return STATUS_DEVICE_BUSY;",
		"InterlockedExchange64(&endpointContext->LastInputSequence",
		"RtlCopyMemory(endpointContext->InputReport",
		"if ((input->Flags & VIIPER_UDE_INPUT_REPORT_TRANSITION) != 0) {",
		"InterlockedIncrement(&endpointContext->InputTransitionCount);",
		"WdfIoQueueRetrieveNextRequest(endpointContext->Queue")
	ready := normalizedContract(nativeCFunction(t, device, "ViiperEvtFastInputQueueReady"))
	requireContractOrder(t, ready,
		"ViiperPrepareCachedInputUrb(endpoint, request);",
		"&endpointContext->CachedDeliveryPending",
		"&endpointContext->InputTransitionCount",
		"&endpointContext->InputSnapshotPending",
		"ViiperCompleteRetrievedInputUrb(endpoint, request, completionStatus);")
	prepare := normalizedContract(nativeCFunction(t, device, "ViiperPrepareCachedInputUrb"))
	requireContractOrder(t, prepare,
		"if (InterlockedCompareExchange(&endpointContext->InputTransitionCount",
		"report = endpointContext->InputTransitionReports",
		"ViiperCopyTransferBuffer(Request, urb, report, reportLength, TRUE)",
		"if (!NT_SUCCESS(status))",
		"UdecxUrbSetBytesCompleted(Request, reportLength);",
		"InterlockedDecrement(&endpointContext->InputTransitionCount)")
}

func TestNativeBrokerFaultFencesAdmissionAndPublication(t *testing.T) {
	broker := nativeContractSource(t, "native", "udecx", "driver", "Broker.c")

	allocate := normalizedContract(nativeCFunction(t, broker, "ViiperAllocatePendingSlot"))
	requireContractOrder(t, allocate,
		"WdfSpinLockAcquire(ControllerContext->BrokerLock);",
		"ControllerContext->BrokerFaulted",
		"pending->Request = Request;")

	dispatch := normalizedContract(nativeCFunction(t, broker, "ViiperDispatchAvailable"))
	requireContractOrder(t, dispatch,
		"ViiperDispatchNotificationEvents(Controller);",
		"controllerContext->BrokerFaulted",
		"controllerContext->NextDispatchSlot + index")

	cancel := normalizedContract(nativeCFunction(t, broker, "ViiperQueueCancelEventLocked"))
	requireContractOrder(t, cancel,
		"if (!Pending->PublishedToOwner)",
		"ControllerContext->BrokerFaulted",
		"ControllerContext->NotificationCount")

	for _, function := range []string{
		"ViiperQueueEndpointLifecycleEvent",
		"ViiperQueueDeviceLifecycleEvent",
		"ViiperQueueInterfaceLifecycleEvent",
	} {
		lifecycle := normalizedContract(nativeCFunction(t, broker, function))
		requireContractOrder(t, lifecycle,
			"active = ownerActive && InterlockedCompareExchange( &controllerContext->BrokerFaulted",
			"queued = active &&",
			"faulted = ownerActive && InterlockedCompareExchange( &controllerContext->BrokerFaulted",
			"WdfSpinLockRelease(controllerContext->BrokerLock);",
			"if (queued || faulted)",
			"ViiperDispatchNotificationEvents(deviceContext->Controller);")
	}

	acknowledged := normalizedContract(nativeCFunction(t, broker, "ViiperQueueAcknowledgedLifecycleEvent"))
	requireContractOrder(t, acknowledged,
		"controllerContext->BrokerFaulted",
		"ViiperFaultBrokerLocked(controllerContext)",
		"faulted = ownerActive && InterlockedCompareExchange( &controllerContext->BrokerFaulted",
		"WdfSpinLockRelease(controllerContext->BrokerLock);",
		"if (NT_SUCCESS(status) || faulted)",
		"ViiperDispatchNotificationEvents(deviceContext->Controller);")
}

func TestNativeLifecycleNotificationsPublishCanonicalEmptyTail(t *testing.T) {
	broker := nativeContractSource(t, "native", "udecx", "driver", "Broker.c")
	dispatch := normalizedContract(nativeCFunction(t, broker, "ViiperDispatchNotificationEvents"))
	requireContractOrder(t, dispatch,
		"operation->Header.Size = sizeof(*operation);",
		"operation->DeviceSequence = event.DeviceSequence;",
		"operation->IsoPacketsOffset = sizeof(*operation);",
		"operation->PayloadOffset = sizeof(*operation);",
		"WdfRequestSetInformation(dequeueRequest, sizeof(*operation));")
}

func TestNativeManualDequeueCancellationRetiresAccounting(t *testing.T) {
	controller := nativeContractSource(t, "native", "udecx", "driver", "Controller.c")
	header := nativeContractSource(t, "native", "udecx", "driver", "ViiperUde.h")
	createQueues := normalizedContract(nativeCFunction(t, controller, "ViiperCreateQueues"))
	requireContractOrder(t, createQueues,
		"WDF_IO_QUEUE_CONFIG_INIT(&queueConfig, WdfIoQueueDispatchManual);",
		"queueConfig.EvtIoCanceledOnQueue = ViiperEvtDequeueCanceledOnQueue;",
		"WdfIoQueueCreate(Device, &queueConfig")
	if !strings.Contains(header,
		"EVT_WDF_IO_QUEUE_IO_CANCELED_ON_QUEUE ViiperEvtDequeueCanceledOnQueue;") {
		t.Fatal("manual dequeue cancellation callback lost its KMDF declaration")
	}
	cancel := normalizedContract(nativeCFunction(t, controller, "ViiperEvtDequeueCanceledOnQueue"))
	requireContractOrder(t, cancel,
		"InterlockedDecrement(&context->WaitingDequeueCount);",
		"NT_ASSERT(remaining >= 0);",
		"WdfRequestComplete(Request, STATUS_CANCELLED);")
}

func TestNativeBrokerMixedLaneFairnessModel(t *testing.T) {
	// Exercise the exact round-robin slot selection and per-endpoint-head rule
	// with control, HID/state, speaker ISO, and microphone ISO traffic from
	// several controllers.  Deterministic head cancellations model purge/reset
	// pressure while proving that an unrelated endpoint is never starved.
	const slots = 4096
	type laneKey struct {
		device   int
		endpoint byte
	}
	type admission struct {
		lane     laneKey
		sequence int
		queued   bool
		linked   bool
	}

	endpoints := []byte{0x00, 0x01, 0x02, 0x82}
	pending := make([]admission, slots)
	queues := make(map[laneKey][]int)
	allocated := 0
	for round := 1; round <= 8; round++ {
		for device := 0; device < 8; device++ {
			for _, endpoint := range endpoints {
				lane := laneKey{device: device, endpoint: endpoint}
				pending[allocated] = admission{
					lane: lane, sequence: round, queued: true, linked: true,
				}
				queues[lane] = append(queues[lane], allocated)
				allocated++
			}
		}
	}

	// Cancel selected heads before dispatch, exactly like the kernel unlink
	// transition: remove the old head and expose its same-endpoint successor.
	for lane, queue := range queues {
		if (lane.device+int(lane.endpoint))%7 == 0 {
			pending[queue[0]].linked = false
			pending[queue[0]].queued = false
			queues[lane] = queue[1:]
		}
	}

	cursor := 0
	delivered := make(map[laneKey][]int)
	remaining := 0
	for _, queue := range queues {
		remaining += len(queue)
	}
	maxInspections := 0
	totalInspections := 0
	for remaining != 0 {
		selected := -1
		inspections := 0
		for offset := 0; offset < slots; offset++ {
			inspections++
			candidate := (cursor + offset) % slots
			item := pending[candidate]
			queue := queues[item.lane]
			if item.queued && item.linked && len(queue) != 0 && queue[0] == candidate {
				selected = candidate
				break
			}
		}
		if selected < 0 {
			t.Fatalf("mixed native traffic stranded %d endpoint admissions", remaining)
		}
		if inspections > maxInspections {
			maxInspections = inspections
		}
		totalInspections += inspections
		item := pending[selected]
		delivered[item.lane] = append(delivered[item.lane], item.sequence)
		queue := queues[item.lane]
		queues[item.lane] = queue[1:]
		pending[selected].linked = false
		pending[selected].queued = false
		cursor = (selected + 1) % slots
		remaining--
	}

	for lane, sequences := range delivered {
		for index := 1; index < len(sequences); index++ {
			if sequences[index] != sequences[index-1]+1 {
				t.Fatalf("lane %+v lost FIFO order: %v", lane, sequences)
			}
		}
	}
	if len(delivered) != 8*len(endpoints) {
		t.Fatalf("only %d/%d independent lanes made progress", len(delivered), 8*len(endpoints))
	}
	// The independent allocation/dispatch cursors make every healthy admission
	// the first inspected slot.  Each of the four deliberately canceled heads
	// costs one extra inspection, never a controller-table wrap.
	if maxInspections != 2 || totalInspections != allocated {
		t.Fatalf("mixed native traffic inspected max=%d total=%d, want max=2 total=%d",
			maxInspections, totalInspections, allocated)
	}
}

func TestNativeFastInputUsesSharedIndexedLifetimeAdmission(t *testing.T) {
	controller := nativeContractSource(t, "native", "udecx", "driver", "Controller.c")
	broker := nativeContractSource(t, "native", "udecx", "driver", "Broker.c")
	device := nativeContractSource(t, "native", "udecx", "driver", "Device.c")
	header := nativeContractSource(t, "native", "udecx", "driver", "ViiperUde.h")
	inf := nativeContractSource(t, "native", "udecx", "package", "ViiperUde.inf")

	owner := normalizedContract(nativeCFunction(t, broker, "ViiperValidateBrokerOwner"))
	if strings.Contains(owner, "WdfWaitLockAcquire") ||
		strings.Contains(owner, "controllerContext->OwnerFile") ||
		strings.Contains(owner, "controllerContext->CleanupInProgress") {
		t.Fatalf("fast owner validation still joins controller-wide cleanup state: %s", owner)
	}
	for _, required := range []string{
		"WdfRequestGetFileObject(Request)",
		"fileContext->BrokerOwner",
		"fileContext->Negotiated",
		"fileContext->Closing",
	} {
		if !strings.Contains(owner, required) {
			t.Fatalf("lock-free owner validation lost %q", required)
		}
	}

	submit := normalizedContract(nativeCFunction(t, device, "ViiperSubmitInputReport"))
	for _, forbidden := range []string{
		"ViiperAcquireDeviceLockExclusive", "WdfObjectReference(endpoint)",
		"WdfObjectDereference(endpoint)",
		"for (index = 0; index < VIIPER_UDE_MAX_DEVICES",
	} {
		if strings.Contains(submit, forbidden) {
			t.Fatalf("fast input retains hot-path work %q: %s", forbidden, submit)
		}
	}
	requireContractOrder(t, submit,
		"ViiperAcquireDeviceLockShared(controllerContext);",
		"ViiperFindInputDeviceLocked(controllerContext, input->DeviceId);",
		"deviceContext->OwnerFile == ownerFile",
		"deviceContext->Generation == input->Generation",
		"WdfSpinLockAcquire(controllerContext->BrokerLock);",
		"endpointContext->Purging",
		"ViiperEndpointOperationStarted(endpoint);",
		"WdfSpinLockRelease(controllerContext->BrokerLock);",
		"ViiperReleaseDeviceLockShared(controllerContext);",
		"WdfWaitLockAcquire(endpointContext->InputLock, NULL);")
	requireContractOrder(t, submit,
		"ViiperPrepareCachedInputUrb(endpoint, urbRequest);",
		"WdfWaitLockRelease(endpointContext->InputLock);",
		"ViiperCompleteRetrievedInputUrb(endpoint, urbRequest, status);")
	requireContractOrder(t, submit,
		"endpointContext->LastInputSequence",
		"RtlCopyMemory(endpointContext->InputReport, payload, input->PayloadLength);",
		"endpointContext->InputReportLength = input->PayloadLength;",
		"InterlockedExchange(&endpointContext->InputReportValid, TRUE);",
		"InterlockedIncrement64(&controllerContext->InputReportsSubmitted);",
		"WdfIoQueueRetrieveNextRequest(endpointContext->Queue, &urbRequest);",
		"endpointContext->CachedDeliveryPending")
	for _, lifecycleGate := range []string{
		"controllerContext->ShuttingDown",
		"deviceContext->InD0",
		"deviceContext->Purging",
		"deviceContext->Resetting",
		"endpointContext->Purging",
		"endpointContext->Resetting",
	} {
		if !strings.Contains(submit, lifecycleGate) {
			t.Fatalf("fast input admission lost lifecycle gate %q", lifecycleGate)
		}
	}

	find := normalizedContract(nativeCFunction(t, device, "ViiperFindInputDeviceLocked"))
	requireContractOrder(t, find,
		"count = ControllerContext->InputDeviceCount;",
		"while (count != 0)",
		"candidate = first + step;",
		"ControllerContext->InputDevices[candidate]",
		"return ControllerContext->InputDevices[first];")
	if strings.Contains(find, "ControllerContext->Devices[") {
		t.Fatalf("input lookup fell back to the physical O(32) table: %s", find)
	}

	if !strings.Contains(header, "EX_PUSH_LOCK DeviceLock;") ||
		!strings.Contains(header, "UDECXUSBDEVICE InputDevices[VIIPER_UDE_MAX_DEVICES];") ||
		!strings.Contains(controller, "ExInitializePushLock(&context->DeviceLock);") {
		t.Fatal("controller lost its shared input index or push-lock initialization")
	}
	sharedAcquire := normalizedContract(nativeCFunction(t, header, "ViiperAcquireDeviceLockShared"))
	sharedRelease := normalizedContract(nativeCFunction(t, header, "ViiperReleaseDeviceLockShared"))
	exclusiveAcquire := normalizedContract(nativeCFunction(t, header, "ViiperAcquireDeviceLockExclusive"))
	exclusiveRelease := normalizedContract(nativeCFunction(t, header, "ViiperReleaseDeviceLockExclusive"))
	requireContractOrder(t, sharedAcquire,
		"KeEnterCriticalRegion();", "ExAcquirePushLockShared(&ControllerContext->DeviceLock);")
	requireContractOrder(t, sharedRelease,
		"ExReleasePushLockShared(&ControllerContext->DeviceLock);", "KeLeaveCriticalRegion();")
	requireContractOrder(t, exclusiveAcquire,
		"KeEnterCriticalRegion();", "ExAcquirePushLockExclusive(&ControllerContext->DeviceLock);")
	requireContractOrder(t, exclusiveRelease,
		"ExReleasePushLockExclusive(&ControllerContext->DeviceLock);", "KeLeaveCriticalRegion();")
	if !strings.Contains(header, "_IRQL_requires_max_(APC_LEVEL)") ||
		!strings.Contains(header, "Normal shared acquisition waits behind an exclusive") {
		t.Fatal("push-lock IRQL/APC or writer-preference contract is undocumented")
	}
	queues := normalizedContract(nativeCFunction(t, controller, "ViiperCreateQueues"))
	requireContractOrder(t, queues,
		"attributes.ExecutionLevel = WdfExecutionLevelPassive;",
		"attributes.SynchronizationScope = WdfSynchronizationScopeNone;",
		"WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(&queueConfig, WdfIoQueueDispatchParallel);")
	if !strings.Contains(inf, "NTamd64.10.0...17763") {
		t.Fatal("driver platform floor no longer proves EX_PUSH_LOCK API availability")
	}
}

func TestNativeEndpointRundownPrecedesCleanupAndDPCMayRunImmediately(t *testing.T) {
	broker := nativeContractSource(t, "native", "udecx", "driver", "Broker.c")
	device := nativeContractSource(t, "native", "udecx", "driver", "Device.c")

	started := normalizedContract(nativeCFunction(t, broker, "ViiperEndpointOperationStarted"))
	requireContractOrder(t, started,
		"if (active == 0)",
		"KeClearEvent(&endpointContext->OperationsDrained);",
		"InterlockedIncrement(&endpointContext->ActiveOperations);")
	completedLocked := normalizedContract(nativeCFunction(
		t, broker, "ViiperEndpointOperationCompletedLocked"))
	requireContractOrder(t, completedLocked,
		"InterlockedDecrement(&endpointContext->ActiveOperations);",
		"if (remaining == 0)",
		"KeSetEvent(&endpointContext->OperationsDrained, IO_NO_INCREMENT, FALSE);")
	completed := normalizedContract(nativeCFunction(t, broker, "ViiperEndpointOperationCompleted"))
	requireContractOrder(t, completed,
		"WdfSpinLockAcquire(controllerContext->BrokerLock);",
		"ViiperEndpointOperationCompletedLocked(Endpoint);",
		"WdfSpinLockRelease(controllerContext->BrokerLock);")
	if got := strings.Count(broker+device,
		"InterlockedIncrement(&endpointContext->ActiveOperations)"); got != 1 {
		t.Fatalf("ActiveOperations has %d increment sites, want one BrokerLock-owned transition", got)
	}
	if got := strings.Count(broker+device,
		"InterlockedDecrement(&endpointContext->ActiveOperations)"); got != 1 {
		t.Fatalf("ActiveOperations has %d decrement sites, want one BrokerLock-owned transition", got)
	}
	startedCalls := regexp.MustCompile(`ViiperEndpointOperationStarted\s*\([^)]*\)\s*;`)
	if got := len(startedCalls.FindAllString(broker+device, -1)); got != 5 {
		t.Fatalf("endpoint rundown has %d admission call sites, want four callback admissions plus the ReadyNotify DPC handoff", got)
	}

	for _, name := range []string{
		"ViiperEvtFastInputQueueReady",
		"ViiperSubmitInputReport",
	} {
		admission := normalizedContract(nativeCFunction(t, device, name))
		requireContractOrder(t, admission,
			"WdfSpinLockAcquire(controllerContext->BrokerLock);",
			"ViiperEndpointOperationStarted(endpoint);",
			"WdfSpinLockRelease(controllerContext->BrokerLock);")
	}
	ready := normalizedContract(nativeCFunction(t, device, "ViiperEvtFastInputQueueReady"))
	requireContractOrder(t, ready,
		"WdfSpinLockAcquire(controllerContext->BrokerLock);",
		"ViiperEndpointOperationStarted(endpoint);",
		"WdfSpinLockRelease(controllerContext->BrokerLock);",
		"WdfWaitLockAcquire(endpointContext->InputLock, NULL);")
	for _, name := range []string{"ViiperEvtUrbCanceledOnQueue", "ViiperQueueUrb"} {
		admission := normalizedContract(nativeCFunction(t, broker, name))
		requireContractOrder(t, admission,
			"WdfSpinLockAcquire(controllerContext->BrokerLock);",
			"ViiperEndpointOperationStarted(endpoint);",
			"WdfSpinLockRelease(controllerContext->BrokerLock);")
	}

	purge := normalizedContract(nativeCFunction(t, device, "ViiperEvtEndpointPurge"))
	requireContractOrder(t, purge,
		"WdfSpinLockAcquire(controllerContext->BrokerLock);",
		"InterlockedExchange(&endpointContext->Purging, TRUE);",
		"WdfSpinLockRelease(controllerContext->BrokerLock);",
		"ViiperPurgeEndpointOperations(Endpoint, STATUS_DEVICE_NOT_READY);",
		"WdfIoQueuePurge(endpointContext->Queue, ViiperEvtEndpointQueuePurged, Endpoint);")
	createQueue := normalizedContract(nativeCFunction(t, device, "ViiperCreateEndpointQueue"))
	if !strings.Contains(createQueue,
		"UdecxUsbEndpointSetWdfIoQueue(Endpoint, endpointContext->Queue);") {
		t.Fatal("endpoint purge lost its explicitly associated WDF queue")
	}
	purgeComplete := normalizedContract(nativeCFunction(t, device, "ViiperEvtEndpointQueuePurged"))
	requireContractOrder(t, purgeComplete,
		"KeWaitForSingleObject( &endpointContext->OperationsDrained",
		"endpointContext->ActiveOperations",
		"ViiperInvalidateEndpointInputReport(endpoint);",
		"UdecxUsbEndpointPurgeComplete(endpoint);")
	resetWork := normalizedContract(nativeCFunction(t, device, "ViiperEvtEndpointResetWorkItem"))
	requireContractOrder(t, resetWork,
		"resetCurrent = ViiperQuiesceResetByIdentity(",
		"if (!resetCurrent)",
		"WdfRequestComplete(request, STATUS_DEVICE_NOT_READY);",
		"ViiperInvalidateEndpointInputReport(endpoint);",
		"ViiperQueueAcknowledgedEndpointLifecycleEvent(")
	start := normalizedContract(nativeCFunction(t, device, "ViiperEvtEndpointStart"))
	if !strings.Contains(start, "ViiperActivateEndpoint(Endpoint, TRUE);") {
		t.Fatal("explicit endpoint START no longer performs the KMDF queue transition")
	}
	activate := normalizedContract(nativeCFunction(t, device, "ViiperActivateEndpoint"))
	requireContractOrder(t, activate,
		"InterlockedExchange(&endpointContext->Purging, FALSE);",
		"endpointContext->StartAnnounced, TRUE, FALSE",
		"WdfIoQueueStart(endpointContext->Queue);",
		"ViiperQueueEndpointLifecycleEvent( Endpoint, ViiperUdeOperationEndpointStart);")

	cleanup := normalizedContract(nativeCFunction(t, device, "ViiperEvtEndpointCleanup"))
	requireContractOrder(t, cleanup,
		"ViiperAcquireDeviceLockExclusive(controllerContext);",
		"endpointContext->ActiveOperations",
		"ViiperInvalidateEndpointInputReport(endpoint);",
		"deviceContext->Endpoints[address] = WDF_NO_HANDLE;",
		"ViiperReleaseDeviceLockExclusive(controllerContext);")
	if strings.Contains(cleanup, "KeWaitForSingleObject") {
		t.Fatalf("EvtCleanup attempts a late wait after KMDF made the object inaccessible: %s", cleanup)
	}

	queueCompletion := normalizedContract(nativeCFunction(t, broker, "ViiperQueueUrbCompletion"))
	if strings.Contains(queueCompletion, "WdfObjectReference(Endpoint)") {
		t.Fatal("terminal DPC lifetime still assumes a WDF reference postpones EvtCleanup")
	}
	dpc := normalizedContract(nativeCFunction(t, broker, "ViiperEvtCompletionDpc"))
	requireContractOrder(t, dpc,
		"UdecxUrbCompleteWithNtStatus(request, completionStatus);",
		"ViiperEndpointOperationCompletedLocked(endpoint);",
		"WdfSpinLockRelease(controllerContext->BrokerLock);",
		"WdfObjectDereference(request);")
	if strings.Contains(dpc, "WdfObjectDereference(endpoint)") {
		t.Fatal("completion DPC touches the endpoint after releasing its final rundown owner")
	}
}

func TestNativeUdeHandleRevocationPrecedesPlugOutAndCleanup(t *testing.T) {
	device := nativeContractSource(t, "native", "udecx", "driver", "Device.c")

	destroy := normalizedContract(nativeCFunction(t, device, "ViiperDestroyVirtualDevice"))
	requireContractOrder(t, destroy,
		"ViiperBeginRemoveDevice(",
		"UdecxUsbDevicePlugOutAndDelete(device);")
	afterPlugOut := destroy[strings.Index(destroy, "UdecxUsbDevicePlugOutAndDelete(device);")+len("UdecxUsbDevicePlugOutAndDelete(device);"):]
	if strings.Contains(afterPlugOut, "ViiperGetDeviceContext(device)") ||
		strings.Contains(afterPlugOut, "WdfObjectReference(device)") {
		t.Fatalf("destroy path accesses a consumed UDE handle after PlugOutAndDelete: %s", afterPlugOut)
	}

	shutdown := normalizedContract(nativeCFunction(t, device, "ViiperBeginControllerShutdown"))
	requireContractOrder(t, shutdown,
		"ViiperRemoveInputDeviceLocked(controllerContext, device);",
		"controllerContext->Devices[index] = WDF_NO_HANDLE;",
		"ViiperReleaseDeviceLockExclusive(controllerContext);",
		"UdecxUsbDevicePlugOutAndDelete(devices[index]);")
	cleanup := normalizedContract(nativeCFunction(t, device, "ViiperEvtEndpointCleanup"))
	requireContractOrder(t, cleanup,
		"endpointContext->ActiveOperations",
		"deviceContext->Endpoints[address] = WDF_NO_HANDLE;")
}

func TestNativeDeviceAndBrokerLockOrderNeverReverses(t *testing.T) {
	broker := nativeContractSource(t, "native", "udecx", "driver", "Broker.c")
	device := nativeContractSource(t, "native", "udecx", "driver", "Device.c")
	functionName := regexp.MustCompile(`(?m)^([A-Za-z_][A-Za-z0-9_]*)\(\r?$`)

	// The only permitted nesting is DeviceLock -> BrokerLock. For every direct
	// DeviceLock acquisition, prove there is no unmatched BrokerLock acquisition
	// earlier in the same function body.
	for _, source := range []string{broker, device} {
		for _, match := range functionName.FindAllStringSubmatch(source, -1) {
			name := match[1]
			body := normalizedContract(nativeCFunction(t, source, name))
			for _, acquire := range []string{
				"ViiperAcquireDeviceLockShared(",
				"ViiperAcquireDeviceLockExclusive(",
			} {
				cursor := 0
				for {
					offset := strings.Index(body[cursor:], acquire)
					if offset < 0 {
						break
					}
					at := cursor + offset
					prefix := body[:at]
					brokerAcquire := strings.LastIndex(prefix, "WdfSpinLockAcquire(")
					brokerRelease := strings.LastIndex(prefix, "WdfSpinLockRelease(")
					if brokerAcquire > brokerRelease {
						t.Fatalf("%s reverses global lock order BrokerLock -> DeviceLock: %s", name, body)
					}
					cursor = at + len(acquire)
				}
			}
		}
	}

	for _, name := range []string{
		"ViiperBeginRemoveDevice",
		"ViiperBeginControllerShutdown",
		"ViiperSubmitInputReport",
	} {
		body := normalizedContract(nativeCFunction(t, device, name))
		deviceAcquire := "ViiperAcquireDeviceLockExclusive("
		deviceRelease := "ViiperReleaseDeviceLockExclusive("
		if name == "ViiperSubmitInputReport" {
			deviceAcquire = "ViiperAcquireDeviceLockShared("
			deviceRelease = "ViiperReleaseDeviceLockShared("
		}
		requireContractOrder(t, body,
			deviceAcquire,
			"WdfSpinLockAcquire(",
			"WdfSpinLockRelease(",
			deviceRelease)
	}

	virtualCleanup := normalizedContract(nativeCFunction(t, device, "ViiperEvtVirtualDeviceCleanup"))
	requireContractOrder(t, virtualCleanup,
		"WdfSpinLockAcquire(controllerContext->BrokerLock);",
		"WdfSpinLockRelease(controllerContext->BrokerLock);",
		"ViiperReleaseDeviceSlot(controllerContext, device, deviceContext->Slot);")
	management := normalizedContract(nativeCFunction(t, broker, "ViiperCompleteManagementOperation"))
	firstRelease := strings.Index(management,
		"WdfSpinLockRelease(ControllerContext->BrokerLock);")
	resetProof := strings.Index(management, "ViiperQuiesceResetByIdentity(")
	if firstRelease < 0 || resetProof < firstRelease {
		t.Fatalf("management path acquires the reset identity fence before releasing BrokerLock: %s", management)
	}
}

func TestNativeEndpointRundownRejectsOldClearIncrementRace(t *testing.T) {
	// Old ordering: Start clears first, Completion wins 1 -> 0 and signals,
	// then Start increments. A waiter can observe signaled while active == 1.
	oldActive := 1
	oldSignaled := false
	oldSignaled = false
	oldActive--
	if oldActive == 0 {
		oldSignaled = true
	}
	oldActive++
	if oldActive != 1 || !oldSignaled {
		t.Fatalf("old adversarial schedule was not reproduced: active=%d signaled=%t",
			oldActive, oldSignaled)
	}

	type rundown struct {
		active   int
		signaled bool
	}
	startLocked := func(state *rundown) {
		if state.active == 0 {
			state.signaled = false
		}
		state.active++
	}
	completeLocked := func(state *rundown) {
		state.active--
		if state.active == 0 {
			state.signaled = true
		}
	}

	for _, completionFirst := range []bool{false, true} {
		state := rundown{active: 1, signaled: false}
		if completionFirst {
			completeLocked(&state)
			startLocked(&state)
		} else {
			startLocked(&state)
			completeLocked(&state)
		}
		if state.active != 1 || state.signaled {
			t.Fatalf("serialized schedule completionFirst=%t left active=%d signaled=%t",
				completionFirst, state.active, state.signaled)
		}
	}
}

func TestNativeFastInputIndexIdentityReuseAndComparisonBound(t *testing.T) {
	type identity struct {
		deviceID   uint64
		owner      int
		generation uint32
		handle     int
	}
	var index []identity
	insert := func(value identity) bool {
		position := 0
		for position < len(index) && index[position].deviceID < value.deviceID {
			position++
		}
		if position < len(index) && index[position].deviceID == value.deviceID {
			return false
		}
		index = append(index, identity{})
		copy(index[position+1:], index[position:])
		index[position] = value
		return true
	}
	removeHandle := func(handle int) {
		for position := range index {
			if index[position].handle == handle {
				copy(index[position:], index[position+1:])
				index = index[:len(index)-1]
				return
			}
		}
	}
	lookup := func(deviceID uint64) (identity, int, bool) {
		first, count, comparisons := 0, len(index), 0
		for count != 0 {
			step := count / 2
			candidate := first + step
			comparisons++
			if index[candidate].deviceID < deviceID {
				first = candidate + 1
				count -= step + 1
			} else {
				count = step
			}
		}
		if first == len(index) || index[first].deviceID != deviceID {
			return identity{}, comparisons, false
		}
		return index[first], comparisons, true
	}

	// 17 is coprime with 32, producing a deterministic hostile insertion order.
	for n := 0; n < 32; n++ {
		id := uint64((n*17)%32 + 1)
		if !insert(identity{deviceID: id, owner: 7, generation: uint32(id + 100), handle: int(id)}) {
			t.Fatalf("unexpected duplicate device ID %d", id)
		}
	}
	maxComparisons := 0
	for id := uint64(1); id <= 32; id++ {
		got, comparisons, ok := lookup(id)
		if !ok || got.owner != 7 || got.generation != uint32(id+100) {
			t.Fatalf("identity lookup %d returned %+v ok=%t", id, got, ok)
		}
		if comparisons > maxComparisons {
			maxComparisons = comparisons
		}
	}
	for _, absent := range []uint64{0, 33, 1 << 63} {
		if _, comparisons, ok := lookup(absent); ok || comparisons > 6 {
			t.Fatalf("absent lookup %d ok=%t comparisons=%d", absent, ok, comparisons)
		}
	}
	if maxComparisons > 6 || maxComparisons >= 32 {
		t.Fatalf("binary lookup comparisons=%d, want <=6 and below O(32) scan", maxComparisons)
	}

	// A delayed cleanup removes only its exact handle. It cannot revoke a new
	// owner/generation which reused the same logical ID after retirement.
	removeHandle(13)
	if !insert(identity{deviceID: 13, owner: 9, generation: 900, handle: 113}) {
		t.Fatal("retired logical ID could not be reused")
	}
	removeHandle(13) // stale cleanup for the old handle
	got, _, ok := lookup(13)
	if !ok || got.handle != 113 || got.owner != 9 || got.generation != 900 {
		t.Fatalf("stale cleanup revoked successor identity: %+v ok=%t", got, ok)
	}
}

func TestNativeSubmitPurgeResetCancelAndCleanupInterleavings(t *testing.T) {
	type endpoint struct {
		open          bool
		active        int
		purgeWaiting  bool
		purgeComplete bool
		resetWaiting  bool
		resetQueued   bool
		terminalDPCs  int
		cleaned       bool
	}
	admit := func(state *endpoint) bool {
		if !state.open {
			return false
		}
		state.active++
		return true
	}
	closeForPurge := func(state *endpoint) {
		state.open = false
		state.purgeWaiting = true
	}
	tryPurgeComplete := func(state *endpoint) bool {
		if !state.purgeWaiting || state.active != 0 {
			return false
		}
		state.purgeComplete = true
		return true
	}
	closeForReset := func(state *endpoint) {
		state.open = false
		state.resetWaiting = true
	}
	tryQueueReset := func(state *endpoint) bool {
		if !state.resetWaiting || state.active != 0 {
			return false
		}
		state.resetQueued = true
		return true
	}
	runTerminalDPC := func(state *endpoint) {
		state.terminalDPCs++
		state.active--
		if state.active < 0 {
			t.Fatal("terminal DPC released unowned rundown")
		}
	}
	cleanup := func(state *endpoint) bool {
		if !state.purgeComplete || state.active != 0 {
			return false
		}
		state.cleaned = true
		return true
	}

	// Submit wins BrokerLock. Purge closes subsequent admission but cannot pass
	// the mandatory completion DPC which owns the admitted request.
	submitFirst := endpoint{open: true}
	if !admit(&submitFirst) {
		t.Fatal("submit failed before lifecycle closure")
	}
	closeForPurge(&submitFirst)
	if admit(&submitFirst) || tryPurgeComplete(&submitFirst) || cleanup(&submitFirst) {
		t.Fatal("purge passed an admitted submit")
	}
	runTerminalDPC(&submitFirst)
	if !tryPurgeComplete(&submitFirst) || !cleanup(&submitFirst) ||
		submitFirst.terminalDPCs != 1 {
		t.Fatalf("submit-first path failed to drain through DPC: %+v", submitFirst)
	}

	// Purge/remove wins the exclusive lifecycle boundary. A stale report never
	// acquires rundown and cleanup can revoke immediately after PurgeComplete.
	purgeFirst := endpoint{open: true}
	closeForPurge(&purgeFirst)
	if admit(&purgeFirst) || !tryPurgeComplete(&purgeFirst) || !cleanup(&purgeFirst) {
		t.Fatalf("purge-first path admitted stale input: %+v", purgeFirst)
	}

	// Cancellation still crosses the terminal DPC. Endpoint reset waits for the
	// same owner but queues an acknowledged reset instead of PurgeComplete.
	resetCancel := endpoint{open: true}
	if !admit(&resetCancel) {
		t.Fatal("cancelled URB was never admitted")
	}
	closeForReset(&resetCancel)
	if tryQueueReset(&resetCancel) {
		t.Fatal("reset publication passed a cancelled request before its DPC")
	}
	runTerminalDPC(&resetCancel)
	if !tryQueueReset(&resetCancel) || resetCancel.terminalDPCs != 1 {
		t.Fatalf("reset/cancel path failed to drain deterministically: %+v", resetCancel)
	}

	// File cleanup publishes Closing before taking OwnerLock. Either validation
	// read false first (the submit-first case above) or it observes this permanent
	// close and cannot enter a successor owner's device generation.
	closing := true
	ownerMatches, generationMatches := true, true
	if ownerMatches && generationMatches && !closing {
		t.Fatal("post-cleanup owner validation admitted a report")
	}
}
