#pragma once

#if defined(_KERNEL_MODE)
#include <ntdef.h>
#include <devioctl.h>
typedef UCHAR VIIPER_UDE_UINT8;
typedef USHORT VIIPER_UDE_UINT16;
typedef ULONG VIIPER_UDE_UINT32;
typedef ULONGLONG VIIPER_UDE_UINT64;
typedef LONG VIIPER_UDE_INT32;
#define VIIPER_UDE_UINT16_C(value) value##U
#define VIIPER_UDE_UINT32_C(value) value##UL
#elif defined(_WIN32)
#include <stdint.h>
#include <winioctl.h>
typedef uint8_t VIIPER_UDE_UINT8;
typedef uint16_t VIIPER_UDE_UINT16;
typedef uint32_t VIIPER_UDE_UINT32;
typedef uint64_t VIIPER_UDE_UINT64;
typedef int32_t VIIPER_UDE_INT32;
#define VIIPER_UDE_UINT16_C(value) UINT16_C(value)
#define VIIPER_UDE_UINT32_C(value) UINT32_C(value)
#else
#include <stdint.h>
typedef uint8_t VIIPER_UDE_UINT8;
typedef uint16_t VIIPER_UDE_UINT16;
typedef uint32_t VIIPER_UDE_UINT32;
typedef uint64_t VIIPER_UDE_UINT64;
typedef int32_t VIIPER_UDE_INT32;
#define VIIPER_UDE_UINT16_C(value) UINT16_C(value)
#define VIIPER_UDE_UINT32_C(value) UINT32_C(value)
#endif

#define VIIPER_UDE_MAGIC VIIPER_UDE_UINT32_C(0x45445556) /* "VUDE" little-endian */
#define VIIPER_UDE_ABI_MAJOR VIIPER_UDE_UINT16_C(1)
#define VIIPER_UDE_ABI_MINOR VIIPER_UDE_UINT16_C(5)

#define VIIPER_UDE_MAX_DEVICES VIIPER_UDE_UINT32_C(32)
#define VIIPER_UDE_MAX_DESCRIPTOR_BYTES VIIPER_UDE_UINT32_C(262144)
#define VIIPER_UDE_MAX_TRANSFER_BYTES VIIPER_UDE_UINT32_C(1048576)
#define VIIPER_UDE_MAX_ISO_PACKETS VIIPER_UDE_UINT32_C(1024)
#define VIIPER_UDE_MAX_INPUT_REPORT_BYTES VIIPER_UDE_UINT32_C(4096)
#define VIIPER_UDE_MAX_PENDING_OPERATIONS VIIPER_UDE_UINT32_C(4096)

#define VIIPER_UDE_CAP_ISOCHRONOUS VIIPER_UDE_UINT32_C(0x00000001)
#define VIIPER_UDE_CAP_STREAMS VIIPER_UDE_UINT32_C(0x00000002)
#define VIIPER_UDE_CAP_DEVICE_LIFECYCLE VIIPER_UDE_UINT32_C(0x00000004)
#define VIIPER_UDE_CAP_INPUT_REPORTS VIIPER_UDE_UINT32_C(0x00000008)

#if defined(_WIN32)
#define VIIPER_UDE_IOCTL_BASE 0x900
#define IOCTL_VIIPER_UDE_NEGOTIATE CTL_CODE(FILE_DEVICE_UNKNOWN, VIIPER_UDE_IOCTL_BASE + 0, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VIIPER_UDE_CREATE_DEVICE CTL_CODE(FILE_DEVICE_UNKNOWN, VIIPER_UDE_IOCTL_BASE + 1, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VIIPER_UDE_DESTROY_DEVICE CTL_CODE(FILE_DEVICE_UNKNOWN, VIIPER_UDE_IOCTL_BASE + 2, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VIIPER_UDE_DEQUEUE_OPERATION CTL_CODE(FILE_DEVICE_UNKNOWN, VIIPER_UDE_IOCTL_BASE + 3, METHOD_OUT_DIRECT, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VIIPER_UDE_COMPLETE_OPERATION CTL_CODE(FILE_DEVICE_UNKNOWN, VIIPER_UDE_IOCTL_BASE + 4, METHOD_IN_DIRECT, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_VIIPER_UDE_QUERY_STATS CTL_CODE(FILE_DEVICE_UNKNOWN, VIIPER_UDE_IOCTL_BASE + 5, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_VIIPER_UDE_SUBMIT_INPUT_REPORT CTL_CODE(FILE_DEVICE_UNKNOWN, VIIPER_UDE_IOCTL_BASE + 6, METHOD_IN_DIRECT, FILE_READ_DATA | FILE_WRITE_DATA)
#endif

#pragma pack(push, 1)

typedef struct VIIPER_UDE_HEADER {
    VIIPER_UDE_UINT32 Magic;
    VIIPER_UDE_UINT16 Major;
    VIIPER_UDE_UINT16 Minor;
    VIIPER_UDE_UINT32 Size;
    VIIPER_UDE_UINT32 Flags;
} VIIPER_UDE_HEADER;

typedef struct VIIPER_UDE_NEGOTIATE_REQUEST {
    VIIPER_UDE_HEADER Header;
    VIIPER_UDE_UINT64 ClientNonce;
    VIIPER_UDE_UINT32 RequestedCapabilities;
    VIIPER_UDE_UINT32 Reserved;
} VIIPER_UDE_NEGOTIATE_REQUEST;

typedef struct VIIPER_UDE_NEGOTIATE_RESPONSE {
    VIIPER_UDE_HEADER Header;
    VIIPER_UDE_UINT64 ClientNonce;
    VIIPER_UDE_UINT64 DriverNonce;
    VIIPER_UDE_UINT32 Capabilities;
    VIIPER_UDE_UINT32 MaxDevices;
    VIIPER_UDE_UINT32 MaxDescriptorBytes;
    VIIPER_UDE_UINT32 MaxTransferBytes;
    VIIPER_UDE_UINT32 MaxIsoPackets;
    VIIPER_UDE_UINT32 MaxPendingOperations;
} VIIPER_UDE_NEGOTIATE_RESPONSE;

typedef enum VIIPER_UDE_DESCRIPTOR_KIND {
    ViiperUdeDescriptorDevice = 1,
    ViiperUdeDescriptorConfiguration = 2,
    ViiperUdeDescriptorBos = 3,
    ViiperUdeDescriptorString = 4
} VIIPER_UDE_DESCRIPTOR_KIND;

typedef struct VIIPER_UDE_DESCRIPTOR_RECORD {
    VIIPER_UDE_UINT16 Kind;
    VIIPER_UDE_UINT16 Index;
    VIIPER_UDE_UINT16 LanguageId;
    VIIPER_UDE_UINT16 Reserved;
    VIIPER_UDE_UINT32 Offset;
    VIIPER_UDE_UINT32 Length;
} VIIPER_UDE_DESCRIPTOR_RECORD;

typedef struct VIIPER_UDE_CREATE_DEVICE {
    VIIPER_UDE_HEADER Header;
    VIIPER_UDE_UINT64 DeviceId;
    VIIPER_UDE_UINT32 Generation;
    VIIPER_UDE_UINT32 Speed;
    VIIPER_UDE_UINT32 DescriptorCount;
    VIIPER_UDE_UINT32 DescriptorRecordsOffset;
    VIIPER_UDE_UINT32 DescriptorDataOffset;
    VIIPER_UDE_UINT32 DescriptorDataLength;
    VIIPER_UDE_UINT32 MaxPendingOperations;
    VIIPER_UDE_UINT32 Reserved;
} VIIPER_UDE_CREATE_DEVICE;

typedef struct VIIPER_UDE_DEVICE_IDENTITY {
    VIIPER_UDE_HEADER Header;
    VIIPER_UDE_UINT64 DeviceId;
    VIIPER_UDE_UINT32 Generation;
    VIIPER_UDE_UINT32 Reserved;
} VIIPER_UDE_DEVICE_IDENTITY;

typedef enum VIIPER_UDE_OPERATION_KIND {
    ViiperUdeOperationControl = 1,
    ViiperUdeOperationTransfer = 2,
    ViiperUdeOperationEndpointStart = 3,
    ViiperUdeOperationEndpointPurge = 4,
    ViiperUdeOperationEndpointReset = 5,
    ViiperUdeOperationDeviceReset = 6,
    ViiperUdeOperationSetInterface = 7,
    ViiperUdeOperationDeviceD0Entry = 8,
    ViiperUdeOperationDeviceD0Exit = 9,
    ViiperUdeOperationCancel = 10,
    ViiperUdeOperationBrokerFault = 11
} VIIPER_UDE_OPERATION_KIND;

typedef struct VIIPER_UDE_ISO_PACKET {
    VIIPER_UDE_UINT32 Offset;
    VIIPER_UDE_UINT32 Length;
    VIIPER_UDE_INT32 Status;
    VIIPER_UDE_UINT32 Reserved;
} VIIPER_UDE_ISO_PACKET;

typedef struct VIIPER_UDE_OPERATION {
    VIIPER_UDE_HEADER Header;
    VIIPER_UDE_UINT64 Token;
    VIIPER_UDE_UINT64 DeviceId;
    VIIPER_UDE_UINT32 Generation;
    VIIPER_UDE_UINT32 Kind;
    VIIPER_UDE_UINT8 EndpointAddress;
    VIIPER_UDE_UINT8 Direction;
    VIIPER_UDE_UINT8 InterfaceNumber;
    VIIPER_UDE_UINT8 InterfaceSetting;
    VIIPER_UDE_UINT32 UrbFunction;
    VIIPER_UDE_UINT32 TransferFlags;
    VIIPER_UDE_UINT32 StartFrame;
    VIIPER_UDE_UINT32 IsoPacketCount;
    VIIPER_UDE_UINT32 TransferLength;
    VIIPER_UDE_UINT32 PayloadOffset;
    VIIPER_UDE_UINT32 PayloadLength;
    VIIPER_UDE_UINT32 IsoPacketsOffset;
    VIIPER_UDE_UINT8 SetupPacket[8];
    VIIPER_UDE_UINT8 EndpointAttributes;
    VIIPER_UDE_UINT8 EndpointInterval;
    VIIPER_UDE_UINT16 EndpointMaxPacketSize;
    VIIPER_UDE_UINT64 EndpointSequence;
} VIIPER_UDE_OPERATION;

typedef struct VIIPER_UDE_COMPLETION {
    VIIPER_UDE_HEADER Header;
    VIIPER_UDE_UINT64 Token;
    VIIPER_UDE_UINT64 DeviceId;
    VIIPER_UDE_UINT32 Generation;
    VIIPER_UDE_INT32 Status;
    VIIPER_UDE_UINT32 UsbdStatus;
    VIIPER_UDE_UINT32 TransferLength;
    VIIPER_UDE_UINT32 IsoPacketCount;
    VIIPER_UDE_UINT32 PayloadOffset;
    VIIPER_UDE_UINT32 PayloadLength;
    VIIPER_UDE_UINT32 IsoPacketsOffset;
    VIIPER_UDE_UINT32 Reserved;
} VIIPER_UDE_COMPLETION;

typedef struct VIIPER_UDE_INPUT_REPORT {
    VIIPER_UDE_HEADER Header;
    VIIPER_UDE_UINT64 DeviceId;
    VIIPER_UDE_UINT32 Generation;
    VIIPER_UDE_UINT8 EndpointAddress;
    VIIPER_UDE_UINT8 Reserved1[3];
    VIIPER_UDE_UINT32 PayloadOffset;
    VIIPER_UDE_UINT32 PayloadLength;
    VIIPER_UDE_UINT64 Sequence;
} VIIPER_UDE_INPUT_REPORT;

typedef struct VIIPER_UDE_STATS {
    VIIPER_UDE_HEADER Header;
    VIIPER_UDE_UINT64 OperationsDequeued;
    VIIPER_UDE_UINT64 OperationsCompleted;
    VIIPER_UDE_UINT64 OperationsCancelled;
    VIIPER_UDE_UINT64 OperationsPurged;
    VIIPER_UDE_UINT64 LateCompletions;
    VIIPER_UDE_UINT64 InvalidMessages;
    VIIPER_UDE_UINT64 QueueExhaustions;
    VIIPER_UDE_UINT64 IsoPackets;
    VIIPER_UDE_UINT64 BytesToDevice;
    VIIPER_UDE_UINT64 BytesFromDevice;
    VIIPER_UDE_UINT64 NotificationEvents;
    VIIPER_UDE_UINT64 NotificationEventOverflows;
    VIIPER_UDE_UINT32 ActiveDevices;
    VIIPER_UDE_UINT32 PendingOperations;
    VIIPER_UDE_UINT32 WaitingDequeues;
    VIIPER_UDE_UINT32 CleanupRetries;
    VIIPER_UDE_UINT64 InputReportsSubmitted;
    VIIPER_UDE_UINT64 InputReportsCompleted;
} VIIPER_UDE_STATS;

#pragma pack(pop)

#if defined(__cplusplus)
static_assert(sizeof(VIIPER_UDE_HEADER) == 16, "VIIPER_UDE_HEADER ABI drift");
static_assert(sizeof(VIIPER_UDE_NEGOTIATE_REQUEST) == 32, "VIIPER_UDE_NEGOTIATE_REQUEST ABI drift");
static_assert(sizeof(VIIPER_UDE_NEGOTIATE_RESPONSE) == 56, "VIIPER_UDE_NEGOTIATE_RESPONSE ABI drift");
static_assert(sizeof(VIIPER_UDE_DESCRIPTOR_RECORD) == 16, "VIIPER_UDE_DESCRIPTOR_RECORD ABI drift");
static_assert(sizeof(VIIPER_UDE_CREATE_DEVICE) == 56, "VIIPER_UDE_CREATE_DEVICE ABI drift");
static_assert(sizeof(VIIPER_UDE_DEVICE_IDENTITY) == 32, "VIIPER_UDE_DEVICE_IDENTITY ABI drift");
static_assert(sizeof(VIIPER_UDE_ISO_PACKET) == 16, "VIIPER_UDE_ISO_PACKET ABI drift");
static_assert(sizeof(VIIPER_UDE_OPERATION) == 96, "VIIPER_UDE_OPERATION ABI drift");
static_assert(sizeof(VIIPER_UDE_COMPLETION) == 72, "VIIPER_UDE_COMPLETION ABI drift");
static_assert(sizeof(VIIPER_UDE_INPUT_REPORT) == 48, "VIIPER_UDE_INPUT_REPORT ABI drift");
static_assert(sizeof(VIIPER_UDE_STATS) == 144, "VIIPER_UDE_STATS ABI drift");
#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(VIIPER_UDE_HEADER) == 16, "VIIPER_UDE_HEADER ABI drift");
_Static_assert(sizeof(VIIPER_UDE_NEGOTIATE_REQUEST) == 32, "VIIPER_UDE_NEGOTIATE_REQUEST ABI drift");
_Static_assert(sizeof(VIIPER_UDE_NEGOTIATE_RESPONSE) == 56, "VIIPER_UDE_NEGOTIATE_RESPONSE ABI drift");
_Static_assert(sizeof(VIIPER_UDE_DESCRIPTOR_RECORD) == 16, "VIIPER_UDE_DESCRIPTOR_RECORD ABI drift");
_Static_assert(sizeof(VIIPER_UDE_CREATE_DEVICE) == 56, "VIIPER_UDE_CREATE_DEVICE ABI drift");
_Static_assert(sizeof(VIIPER_UDE_DEVICE_IDENTITY) == 32, "VIIPER_UDE_DEVICE_IDENTITY ABI drift");
_Static_assert(sizeof(VIIPER_UDE_ISO_PACKET) == 16, "VIIPER_UDE_ISO_PACKET ABI drift");
_Static_assert(sizeof(VIIPER_UDE_OPERATION) == 96, "VIIPER_UDE_OPERATION ABI drift");
_Static_assert(sizeof(VIIPER_UDE_COMPLETION) == 72, "VIIPER_UDE_COMPLETION ABI drift");
_Static_assert(sizeof(VIIPER_UDE_INPUT_REPORT) == 48, "VIIPER_UDE_INPUT_REPORT ABI drift");
_Static_assert(sizeof(VIIPER_UDE_STATS) == 144, "VIIPER_UDE_STATS ABI drift");
#endif
